#ifndef CONFIG_H
#define CONFIG_H

#define TICK_PER_180DEG   565267
#define TICK_PER_1M       1051600

#define ASSERV_DIST_MAX_ACCEL 0.03
#define ASSERV_DIST_MAX_SPEED 5.0
#define ASSERV_ANGU_MAX_ACCEL 0.055
#define ASSERV_ANGU_MAX_SPEED 50.0

#define ASSERV_DIST_KP    250
#define ASSERV_DIST_KD    1000
#define ASSERV_DIST_KI    0
#define ASSERV_DIST_IMAX  0

#define ASSERV_ANGU_KP    500
#define ASSERV_ANGU_KD    1000
#define ASSERV_ANGU_KI    0
#define ASSERV_ANGU_IMAX  0

#define LCD_SCHEDULER_PRIO LOWPRIO
#define POSITION_SCHEDULER_PRIO HIGHPRIO
#define POSITION_TRAJECTORY_PRIO (HIGHPRIO - 1)

#define PCM9685_FREQ_HZ 50

#define DC_MOTORS_TYPE DC_MOTORS_TYPE_LMD18200T

#define ROBOT_X 370
#define ROBOT_Y 360
#define ROBOT_WEDGING_BACK_OFFSET 105

#define BAT_WARNING_THRESHOLD_MV 20000
#define BAT_ERROR_THRESHOLD_MV 19000

#define USIR_MASTER
#define STEP_MASTER

#define PRINCIPAL 0
#define SECONDAIRE 1

#define ROBOT PRINCIPAL

#endif// CONFIG_H
