#ifndef STEP_H
#define STEP_H

#include <stdint.h>
#include <config.h>

#define STEP_ID 0x4512
#define STEP_STATUS_BUSY 0x0001

typedef enum
{
  STEP_BOARD_ID,
  STEP_COMMAND,
} step_registers_t;

typedef enum
{
  STEP_ACTION_WAIT,
  STEP_ACTION_RESET_GREEN,
  STEP_ACTION_RESET_YELLOW,
  STEP_ACTION_DISABLE,

  STEP_ACTION_PRETAKE_FIRST_BALL_LEFT,
  STEP_ACTION_PRETAKE_FIRST_BALL_RIGHT,
  STEP_ACTION_TAKE_FIRST_BALL_LEFT,
  STEP_ACTION_TAKE_FIRST_BALL_RIGHT,
  STEP_ACTION_PRETAKE_FIRST_2BALL_LEFT,
  STEP_ACTION_PRETAKE_FIRST_2BALL_RIGHT,
  STEP_ACTION_TAKE_FIRST_2BALL_LEFT,
  STEP_ACTION_TAKE_FIRST_2BALL_RIGHT,

  STEP_ACTION_PREP_SPOT_CENTER,
  STEP_ACTION_PREP_SPOT_LEFT,
  STEP_ACTION_PREP_SPOT_RIGHT,
  STEP_ACTION_TAKE_SPOT_LEFT,
  STEP_ACTION_TAKE_SPOT_RIGHT,
  STEP_ACTION_LEAVE_SPOT_RIGHT,
  STEP_ACTION_LEAVE_SPOT_LEFT,
  STEP_ACTION_LEAVE_SOFT_SPOT_RIGHT,
  STEP_ACTION_LEAVE_SOFT_SPOT_LEFT,
  STEP_ACTION_PRETAKE_SPOT_LEFT,
  STEP_ACTION_PRETAKE_SPOT_RIGHT,

  STEP_ACTION_TAKE_RIGHT,
  STEP_ACTION_PREPFIRST_RIGHT,
  STEP_ACTION_PREPFIRST_LEFT,
  STEP_ACTION_PREP_RIGHT,
  STEP_ACTION_DUMP_LEFT,
  STEP_ACTION_DUMP_RIGHT,
} step_action_t;

void stepInit(void);

#if defined(STEP_MASTER)

void stepWait(void);
void stepAction(step_action_t action);

#elif defined(STEP_SLAVE)

step_action_t stepGetCommand(void);
void stepSetReady(void);

#else
# error "No master/slave step configuration selected"
#endif

#endif// STEP_H

