#include <math.h>
#include <trajectory.h>
#include "pathfinder.h"
#include "../field_2015/field.h"
#include "../position/position.h"

PATHFINDER_MAP pathfinder_map[FIELD_X / FIELD_RESOLUTION][FIELD_Y / FIELD_RESOLUTION] = {
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_ACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_DANGER, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}},
        {{FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}, {FIELD_MAP_ETAT_INACCESSIBLE, PATHFINDER_NOLISTE, 0, {-1, -1, 0, 0}}}
};

void _pathfinderAddToList(PATHFINDER_POINT point, int liste);
int _pathfinderIsOnList(PATHFINDER_POINT point, int liste);
PATHFINDER_POINT _pathfinderGetNext(void);
void _pathfinderGetNeighbours(PATHFINDER_POINT point, PATHFINDER_POINT neighbours [8]);
double _pathfinderGetAngleRobot(PATHFINDER_POINT point);
double _pathfinderGetAngle (PATHFINDER_POINT parent, PATHFINDER_POINT point);
double _pathfinderDeltaAngle(double angle1, double angle2);
int _pathfinderIsAccessible (PATHFINDER_POINT point);
int _pathfinderMalusTerrain (PATHFINDER_POINT point);
double _pathfinderAngleReelToAngleMap(double angle);
double _pathfinderConvertXReelToMap(double x);
double _pathfinderConvertXMapToReel(double x);
double _pathfinderConvertYReelToMap(double y);
double _pathfinderConvertYMapToReel(double y);

void pathfinderInit(void)
{
}

int pathfinderGotoXYmm(double x, double y)
{
  PATHFINDER_POINT start = {_pathfinderConvertXReelToMap(posGetXmm()), _pathfinderConvertYReelToMap(posGetYmm()), 0, 0};
  PATHFINDER_POINT end = {x, y, 0, 0};

  if (!_pathfinderIsAccessible (start) || !_pathfinderIsAccessible (end))
    return 1;

  _pathfinderAddToList(start, PATHFINDER_OPENLIST);

  PATHFINDER_POINT currentNode = _pathfinderGetNext();
  while (currentNode.x != -1 || currentNode.y != -1)
  {
    if (currentNode.x == end.x && currentNode.y == end.y)
      break;

    _pathfinderAddToList(currentNode, PATHFINDER_CLOSELIST);

    PATHFINDER_POINT neighbours[8];
    _pathfinderGetNeighbours(currentNode, neighbours);

    int i;
    for (i = 0; i < 8; ++i)
    {
      PATHFINDER_POINT neighbour = neighbours[i];

      if (neighbour.x == -1 || neighbour.y == -1)
        continue;

      if (_pathfinderIsOnList(neighbour, PATHFINDER_CLOSELIST) || !_pathfinderIsAccessible(neighbour))
        continue;

      int malus_terrain = _pathfinderMalusTerrain(neighbour);
      double newG = pathfinder_map[currentNode.x][currentNode.y].score + neighbour.poids + neighbour.malus + malus_terrain;

      if (pathfinder_map[neighbour.x][neighbour.y].score == 0.0 || newG < pathfinder_map[neighbour.x][neighbour.y].score)
      {
        pathfinder_map [neighbour.x][neighbour.y].score = newG;
        pathfinder_map[neighbour.x][neighbour.y].parent.x = currentNode.x;
        pathfinder_map[neighbour.x][neighbour.y].parent.y = currentNode.y;

        _pathfinderAddToList(neighbour, PATHFINDER_OPENLIST);
      }
    }

    currentNode = _pathfinderGetNext();
  }

  currentNode = _pathfinderGetNext();
  if (currentNode.x != -1 || currentNode.y != -1)
  {
    return 1;
  }

  PATHFINDER_POINT checkpoints[TRAJECTORY_MAX_ORDER];
  int i;
  for (i = 0; i < TRAJECTORY_MAX_ORDER; i++)
  {
    PATHFINDER_POINT point = {-1, -1, 0, 0};
    checkpoints[i] = point;
  }
  
  PATHFINDER_POINT lastNode = end;
  double angle = -1;
  double angle2;
  int cpt = 0;
  while (lastNode.x != start.x || lastNode.y != start.y)
  {
    PATHFINDER_POINT point1, point2;

    point1.x = lastNode.x;
    point1.y = lastNode.y;

    PATHFINDER_MAP point = pathfinder_map [lastNode.x][lastNode.y];

    lastNode.x = point.parent.x;
    lastNode.y = point.parent.y;

    point2.x = lastNode.x;
    point2.y = lastNode.y;

    angle2 = _pathfinderGetAngle (point1, point2);

    if (angle == -1 || angle != angle2)
    {
      PATHFINDER_POINT point = {point1.x * FIELD_RESOLUTION, point1.y * FIELD_RESOLUTION, 0, 0};
      checkpoints [cpt++] = point;
      angle = angle2;
    }
  }
  PATHFINDER_POINT point = {start.x * FIELD_RESOLUTION, start.y * FIELD_RESOLUTION, 0, 0};
  checkpoints [cpt++] = point;

  for (i = TRAJECTORY_MAX_ORDER - 1; i >= 0; i--)
  {
    TRAJECTORY_XY_MM(_pathfinderConvertXMapToReel(checkpoints[i].x), _pathfinderConvertYMapToReel(checkpoints[i].y));
  }

  return 0;
}

void _pathfinderAddToList(PATHFINDER_POINT point, int liste)
{
  pathfinder_map[point.x][point.y].liste = liste;
}

int _pathfinderIsOnList(PATHFINDER_POINT point, int liste)
{
  return pathfinder_map[point.x][point.y].liste == liste;
}

PATHFINDER_POINT _pathfinderGetNext(void)
{
  int i, j;
  double min = -1;
  PATHFINDER_POINT point;

  for (i = 0; i < FIELD_X / FIELD_RESOLUTION ; i++)
  {
    for (j = 0; j < FIELD_Y / FIELD_RESOLUTION; j++)
    {
      if (pathfinder_map[i][j].liste == PATHFINDER_OPENLIST)
      {
        if (min == -1 || pathfinder_map[i][j].score < min)
        {
          min = pathfinder_map[i][j].score;
          point.x = i;
          point.y = j;
        }
      }
    }
  }

  if (min == -1)
  {
    point.x = -1;
    point.y = -1;
  }

  point.poids = 0;
  point.malus = 0;

  return point;
}

void _pathfinderGetNeighbours(PATHFINDER_POINT point, PATHFINDER_POINT neighbours [8])
{
  // On récupère l'angle actuel du robot
  double angle = _pathfinderGetAngleRobot(point);
  double delta_angle;
  double distance;

  // Voisin à 0°
  distance = 1;
  delta_angle = _pathfinderDeltaAngle(angle, 0);
  PATHFINDER_POINT point_up;
  point_up.x = point.x;
  point_up.y = point.y - 1;
  point_up.poids = distance;
  point_up.malus = delta_angle * PATHFINDER_MALUS_ROTATION;
  if (point_up.y < 0)
  {
    point_up.x = -1;
    point_up.y = -1;
  }

  // Voisin à 45°
  distance = M_SQRT2;
  delta_angle = _pathfinderDeltaAngle(angle, 45);
  PATHFINDER_POINT point_up_right;
  point_up_right.x = point.x + 1;
  point_up_right.y = point.y - 1;
  point_up_right.poids = distance;
  point_up_right.malus = delta_angle * PATHFINDER_MALUS_ROTATION;
  if (point_up_right.y < 0)
  {
    point_up_right.x = -1;
    point_up_right.y = -1;
  }
  if (point_up_right.x > FIELD_X / FIELD_RESOLUTION)
  {
    point_up_right.x = -1;
    point_up_right.y = -1;
  }

  // Voisin à 90°
  distance = 1;
  delta_angle = _pathfinderDeltaAngle(angle, 90);
  PATHFINDER_POINT point_right;
  point_right.x = point.x + 1;
  point_right.y = point.y;
  point_right.poids = distance;
  point_right.malus = delta_angle * PATHFINDER_MALUS_ROTATION;
  if (point_right.x > FIELD_X / FIELD_RESOLUTION)
  {
    point_right.x = -1;
    point_right.y = -1;
  }

  // Voisin à 135°
  distance = M_SQRT2;
  delta_angle = _pathfinderDeltaAngle(angle, 135);
  PATHFINDER_POINT point_down_right;
  point_down_right.x = point.x + 1;
  point_down_right.y = point.y + 1;
  point_down_right.poids = distance;
  point_down_right.malus = delta_angle * PATHFINDER_MALUS_ROTATION;
  if (point_down_right.y >= FIELD_Y / FIELD_RESOLUTION)
  {
    point_down_right.x = -1;
    point_down_right.y = -1;
  }
  if (point_down_right.x > FIELD_X / FIELD_RESOLUTION)
  {
    point_down_right.x = -1;
    point_down_right.y = -1;
  }

  // Voisin à 180°
  distance = 1;
  delta_angle = _pathfinderDeltaAngle(angle, 180);
  PATHFINDER_POINT point_down;
  point_down.x = point.x;
  point_down.y = point.y + 1;
  point_down.poids = distance;
  point_down.malus = delta_angle * PATHFINDER_MALUS_ROTATION;
  if (point_down.y >= FIELD_Y / FIELD_RESOLUTION)
  {
    point_down.x = -1;
    point_down.y = -1;
  }

  // Voisin à -135°
  distance = M_SQRT2;
  delta_angle = _pathfinderDeltaAngle(angle, -135);
  PATHFINDER_POINT point_down_left;
  point_down_left.x = point.x - 1;
  point_down_left.y = point.y + 1;
  point_down_left.poids = distance;
  point_down_left.malus = delta_angle * PATHFINDER_MALUS_ROTATION;
  if (point_down_left.y >= FIELD_Y / FIELD_RESOLUTION)
  {
    point_down_left.x = -1;
    point_down_left.y = -1;
  }
  if (point_down_left.x < 0)
  {
    point_down_left.x = -1;
    point_down_left.y = -1;
  }

  // Voisin à -90°
  distance = 1;
  delta_angle = _pathfinderDeltaAngle(angle, -90);
  PATHFINDER_POINT point_left;
  point_left.x = point.x - 1;
  point_left.y = point.y;
  point_left.poids = distance;
  point_left.malus = delta_angle * PATHFINDER_MALUS_ROTATION;
  if (point_left.x < 0)
  {
    point_left.x = -1;
    point_left.y = -1;
  }

  // Voisin à -45°
  distance = M_SQRT2;
  delta_angle = _pathfinderDeltaAngle(angle, -45);
  PATHFINDER_POINT point_up_left;
  point_up_left.x = point.x - 1;
  point_up_left.y = point.y - 1;
  point_up_left.poids = distance;
  point_up_left.malus = delta_angle * PATHFINDER_MALUS_ROTATION;
  if (point_up_left.y < 0)
  {
    point_up_left.x = -1;
    point_up_left.y = -1;
  }
  if (point_up_left.x < 0)
  {
    point_up_left.x = -1;
    point_up_left.y = -1;
  }

  neighbours[0] = point_up;
  neighbours[1] = point_right;
  neighbours[2] = point_down;
  neighbours[3] = point_left;
  neighbours[4] = point_up_right;
  neighbours[5] = point_down_right;
  neighbours[6] = point_down_left;
  neighbours[7] = point_up_left;
}

double _pathfinderGetAngleRobot(PATHFINDER_POINT point)
{
  double angle;

  // On n'a pas encore commencé le parcours, on récupère donc l'angle actuel du robot
  if (point.x == -1 && point.y == -1)
  {
    angle = _pathfinderAngleReelToAngleMap(posGetAdeg());
    return angle;
  }

  PATHFINDER_MAP mapPoint = pathfinder_map[point.x][point.y];
  PATHFINDER_POINT parent = mapPoint.parent;

  // On n'a pas encore avancé, on récupère donc l'angle actuel du robot
  if (parent.x == -1 && parent.y == -1)
  {
    angle = _pathfinderAngleReelToAngleMap(posGetAdeg());
  }
  else
  {
    angle = _pathfinderGetAngle(parent, point);
  }

  return angle;
}

double _pathfinderGetAngle(PATHFINDER_POINT parent, PATHFINDER_POINT point)
{
  double angle;

  if (parent.x == point.x + 1 && parent.y == point.y)
  {
    angle = -90;
  }
  else if (parent.x == point.x + 1 && parent.y == point.y + 1)
  {
    angle = -45;
  }
  else if (parent.x == point.x && parent.y == point.y + 1)
  {
    angle = 0;
  }
  else if (parent.x == point.x - 1 && parent.y == point.y + 1)
  {
    angle = 45;
  }
  else if (parent.x == point.x - 1 && parent.y == point.y)
  {
    angle = 90;
  }
  else if (parent.x == point.x - 1 && parent.y == point.y - 1)
  {
    angle = 135;
  }
  else if (parent.x == point.x && parent.y == point.y - 1)
  {
    angle = 180;
  }
  else if (parent.x == point.x + 1 && parent.y == point.y - 1)
  {
    angle = -135;
  }
  else
  {
    angle = atan2((point.x - parent.x), (parent.y - point.y)) * 180 / M_PI;
  }

  return angle;
}

double _pathfinderDeltaAngle(double angle1, double angle2)
{
  if (angle1 == -1)
    return 0;
  else
    return angle1 != angle2;
}

int _pathfinderIsAccessible (PATHFINDER_POINT point)
{
  PATHFINDER_MAP pointMap = pathfinder_map[point.x][point.y];

  return pointMap.type != FIELD_MAP_ETAT_INACCESSIBLE;
}

int _pathfinderMalusTerrain (PATHFINDER_POINT point)
{
  PATHFINDER_MAP pointMap = pathfinder_map[point.x][point.y];

  switch (pointMap.type)
  {
    case (FIELD_MAP_ETAT_ACCESSIBLE):
      return 0;
    case (FIELD_MAP_ETAT_DANGER):
      return PATHFINDER_MALUS_TERRAIN;
    case (FIELD_MAP_ETAT_INACCESSIBLE):
    default:
      return -1;
  }
}

double _pathfinderAngleReelToAngleMap(double angle)
{
  if (angle > 90)
  {
    return angle - 360 + 90;
  }
  else
  {
    return angle + 90;
  }
}

double _pathfinderConvertXReelToMap(double x)
{
  return FIELD_X / 2 + x;
}

double _pathfinderConvertXMapToReel(double x)
{
  return x - FIELD_X / 2;
}

double _pathfinderConvertYReelToMap(double y)
{
  return FIELD_Y - y;
}

double _pathfinderConvertYMapToReel(double y)
{
  return FIELD_Y - y;
}