#ifndef CONFIG_H
#define CONFIG_H

#define ROBOT PRINCIPAL
#define EQUIPE GAUCHE

#define PATHFINDER_ALGO DIJKSTRA

#define ROBOT_PRINCIPAL_LARGEUR 360
#define ROBOT_PRINCIPAL_PROFONDEUR 195
#define ROBOT_SECONDAIRE_LARGEUR 200
#define ROBOT_SECONDAIRE_PROFONDEUR 150

#if ROBOT == PRINCIPAL
    #define ROBOT_X ROBOT_PRINCIPAL_LARGEUR
    #define ROBOT_Y ROBOT_PRINCIPAL_PROFONDEUR
#else
    #define ROBOT_X ROBOT_SECONDAIRE_LARGEUR
    #define ROBOT_Y ROBOT_SECONDAIRE_PROFONDEUR
#endif

#endif // CONFIG_H
