#ifndef CONFIG_H
#define CONFIG_H

#define FALSE 0
#define TRUE 1

#define SQRT2 1.414214

#define PRINCIPAL 0
#define SECONDAIRE 1

#define GAUCHE 0
#define DROITE 1

#define ASTAR 0
#define DIJKSTRA 1

#define MANHATTAN 0
#define EUCLIDEAN 1
#define OCTILE 2
#define CHEBYSHEV 3

#define ROBOT SECONDAIRE
#define EQUIPE GAUCHE

#define PATHFINDER_ALGO ASTAR
#define PATHFINDER_HEURISTIQUE MANHATTAN
#define PATHFINDER_COUT_DIAGONALE SQRT2
#define PATHFINDER_WITH_DIAGONALE FALSE
#define PATHFINDER_MALUS_ROTATION 5

#define DIJKSTRA_DEBUG
#define ASTAR_DEBUG
#define ASTAR_DEBUG2

#define FIELD_X 3000
#define FIELD_Y 2000
#define FIELD_RESOLUTION 2
#define FIELD_DANGER_INACCESSIBLE ROBOT_X / 2
#define FIELD_DANGER 50
#define FIELD_MALUS_TERRAIN 1

#define ROBOT_PRINCIPAL_LARGEUR 360
#define ROBOT_PRINCIPAL_PROFONDEUR 195
#define ROBOT_SECONDAIRE_LARGEUR 200
#define ROBOT_SECONDAIRE_PROFONDEUR 150

#if ROBOT == PRINCIPAL
    #define ROBOT_X ROBOT_PRINCIPAL_LARGEUR
    #define ROBOT_Y ROBOT_PRINCIPAL_PROFONDEUR
#else
    #define ROBOT_X ROBOT_SECONDAIRE_LARGEUR
    #define ROBOT_Y ROBOT_SECONDAIRE_PROFONDEUR
#endif

#endif // CONFIG_H
