#ifndef CONFIG_H
#define CONFIG_H

#define TICK_PER_180DEG   10000.0
#define TICK_PER_1M       10000.0

#define ASSERV_DIST_MAX_ACCEL 10.0
#define ASSERV_DIST_MAX_SPEED 10.0
#define ASSERV_ANGU_MAX_ACCEL 10.0
#define ASSERV_ANGU_MAX_SPEED 10.0

#define LCD_SCHEDULER_PRIO LOWPRIO
#define POSITION_SCHEDULER_PRIO HIGHPRIO

#endif// CONFIG_H
