#ifndef CONFIG_H
#define CONFIG_H

#define TICK_PER_180DEG   180000.0
#define TICK_PER_1M       200000.0

#define LCD_SCHEDULER_PRIO LOWPRIO
#define POSITION_SCHEDULER_PRIO HIGHPRIO

#endif// CONFIG_H
