#ifndef CONFIG_H
#define CONFIG_H

#define STEP_SLAVE

#define STEP_LEFT_LIFT_ID   0
#define STEP_RIGHT_LIFT_ID  1
#define STEP_LEFT_SLIDER_ID 2
#define STEP_RIGHT_SLIDER_ID 3

#define STEP_LEFT_LIFT_RESET_OFFSET -2000
#define STEP_RIGHT_LIFT_RESET_OFFSET 2000
#define STEP_LEFT_SLIDER_RESET_OFFSET 4000
#define STEP_RIGHT_SLIDER_RESET_OFFSET -4000

#define STEP_LEFT_LIFT_INIT           350
#define STEP_RIGHT_LIFT_INIT            0
#define STEP_LEFT_SLIDER_INIT           -1000
#define STEP_RIGHT_SLIDER_INIT            1300

#define SERVO_CLAMP_LEFT_CLOSE  800
#define SERVO_CLAMP_LEFT_ALMOST_CLOSE  1300
#define SERVO_CLAMP_LEFT_OPEN  1400
#define SERVO_CLAMP_LEFT_INIT  2200

#define SERVO_CLAMP_RIGHT_CLOSE  735
#define SERVO_CLAMP_RIGHT_ALMOST_CLOSE  1300
#define SERVO_CLAMP_RIGHT_OPEN  1400
#define SERVO_CLAMP_RIGHT_INIT  2200

#define SERVO_SLIDER_RIGHT_OPEN     800
#define SERVO_SLIDER_RIGHT_CLOSE     1900

#define SERVO_SLIDER_LEFT_OPEN     2000
#define SERVO_SLIDER_LEFT_CLOSE     1100

#endif// CONFIG_H
