#ifndef ENCODER_MAGNETIC_CONFIG_H
#define ENCODER_MAGNETIC_CONFIG_H

#define ENCODER_MAGNETIC_NUMBER 2
#define ENCODER_MAGNETIC_SS_PORTS {&PORTE, &PORTE}
#define ENCODER_MAGNETIC_SS_BITS  {0, 1}

#endif// ENCODER_MAGNETIC_CONFIG_H
